apiVersion: apps/v1
kind: Deployment
metadata:
  name: gate-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gate-service
  template:
    metadata:
      labels:
        app: gate-service
    spec:
      containers:
      - name: gate-service
        image: 794acdacb2e0:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: gate-service
spec:
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082
  selector:
    app: gate-service
