apiVersion: apps/v1
kind: Deployment
metadata:
  name: lpr-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lpr-service
  template:
    metadata:
      labels:
        app: lpr-service
    spec:
      containers:
      - name: lpr-service
        image: localhost:5000/parking-lot-system-lpr-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: lpr-service
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: lpr-service
